### ISSUE TITLE
Better error message for reference to API in the same template

### ISSUE THREAD

**Issue by ylynn** [awslabs/serverless-application-model#1038]
**Description:**

Need a better error message for reference to API in the same template

**Steps to reproduce the issue:**

Template:
```
AppStack:
  Type: AWS::Serverless::Application
  Properties:
    ...
AnotherFunction:
  Type: AWS::Serverless::Function
  Properties:
    Events:
     SomeEvent:
      Type: Api
      Properties:
        RestApiId:
          Fn::GetAtt:
          - AppStack
          - Outputs.ApiGatewayId
        ...
```

Fail with an unhandled exception

**Comment by keetonian** [comment]
Looked into this. I think we can update the code about how we find the RestApiId [here](https://github.com/awslabs/serverless-application-model/blob/develop/samtranslator/plugins/api/implicit_api_plugin.py#L223-L232)

Template that reproduces issue:
```yaml
Resources:
  AnotherFunction:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: |
        print('hi')
      Runtime: python3.6
      Handler: index.handler
      Events:
        SomeEvent:
          Type: Api
          Properties:
            RestApiId:
              Fn::GetAtt:
              - AppStack
              - Outputs.ApiGatewayId
            Method: get
            Path: /
```

Output error:
```
ERROR:root:Plugin 'ImplicitApiPlugin' raised an exception: unhashable type: 'dict'
Traceback (most recent call last):
  File "/Users/.../serverless-application-model/bin/../samtranslator/plugins/__init__.py", line 130, in act
    getattr(plugin, method_name)(*args, **kwargs)
  File "/Users/.../serverless-application-model/bin/../samtranslator/plugins/api/implicit_api_plugin.py", line 79, in on_before_transform_template
    self._process_api_events(function, api_events, template, condition)
  File "/Users/.../serverless-application-model/bin/../samtranslator/plugins/api/implicit_api_plugin.py", line 153, in _process_api_events
    api_dict = self.api_conditions.setdefault(api_id, {})
TypeError: unhashable type: 'dict'
Traceback (most recent call last):
  File "bin/sam-translate.py", line 141, in <module>
    transform_template(input_file_path, output_file_path)
  File "bin/sam-translate.py", line 98, in transform_template
    sam_template, {}, ManagedPolicyLoader(iam_client))
  File "/Users/.../serverless-application-model/bin/../samtranslator/translator/transform.py", line 16, in transform
    return translator.translate(input_fragment, parameter_values=parameter_values)
  File "/Users/.../serverless-application-model/bin/../samtranslator/translator/translator.py", line 60, in translate
    sam_plugins=sam_plugins
  File "/Users/.../serverless-application-model/bin/../samtranslator/parser/parser.py", line 13, in parse
    sam_plugins.act(LifeCycleEvents.before_transform_template, sam_template)
  File "/Users/.../serverless-application-model/bin/../samtranslator/plugins/__init__.py", line 136, in act
    raise ex
TypeError: unhashable type: 'dict'
```

**Comment by jlhood** [comment]
This would be a great first issue if someone from the community would like to debug and fix it. @keetonian got to the error/stack trace by running [sam-translate.py](https://github.com/awslabs/serverless-application-model/blob/master/bin/sam-translate.py) on the example template.
