### ISSUE TITLE
Debugging isn't available for java11

### ISSUE THREAD

**Issue by buckett** [awslabs/serverless-application-model#1343]
If you attempt to debug a local lambda function running on java11 with `sam`:

     sam local start-api --template template.yaml -d 8000

you get an error:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/0.37.0/libexec/lib/python3.7/site-packages/samcli/local/docker/lambda_debug_entrypoint.py", line 141, in get_entry_point
    return entrypoint_mapping[runtime]
KeyError: 'java11'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/0.37.0/libexec/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/Cellar/aws-sam-cli/0.37.0/libexec/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/Cellar/aws-sam-cli/0.37.0/libexec/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/Cellar/aws-sam-cli/0.37.0/libexec/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/usr/local/Cellar/aws-sam-cli/0.37.0/libexec/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/Cellar/aws-sam-cli/0.37.0/libexec/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/Cellar/aws-sam-cli/0.37.0/libexec/lib/python3.7/site-packages/samcli/local/apigw/local_apigw_service.py", line 191, in _request_handler
    self.lambda_runner.invoke(route.function_name, event, stdout=stdout_stream_writer, stderr=self.stderr)
  File "/usr/local/Cellar/aws-sam-cli/0.37.0/libexec/lib/python3.7/site-packages/samcli/commands/local/lib/local_lambda.py", line 98, in invoke
    self.local_runtime.invoke(config, event, debug_context=self.debug_context, stdout=stdout, stderr=stderr)
  File "/usr/local/Cellar/aws-sam-cli/0.37.0/libexec/lib/python3.7/site-packages/samcli/local/lambdafn/runtime.py", line 77, in invoke
    debug_options=debug_context,
  File "/usr/local/Cellar/aws-sam-cli/0.37.0/libexec/lib/python3.7/site-packages/samcli/local/docker/lambda_container.py", line 74, in __init__
    entry = LambdaContainer._get_entry_point(runtime, debug_options)
  File "/usr/local/Cellar/aws-sam-cli/0.37.0/libexec/lib/python3.7/site-packages/samcli/local/docker/lambda_container.py", line 202, in _get_entry_point
    options=LambdaContainer._DEBUG_ENTRYPOINT_OPTIONS,
  File "/usr/local/Cellar/aws-sam-cli/0.37.0/libexec/lib/python3.7/site-packages/samcli/local/docker/lambda_debug_entrypoint.py", line 143, in get_entry_point
    raise DebuggingNotSupported("Debugging is not currently supported for {}".format(runtime))
samcli.local.docker.lambda_debug_entrypoint.DebuggingNotSupported: Debugging is not currently supported for java11
```

Debugging in the same way works fine on java8.

**Comment by buckett** [comment]
Ok, it looks like this is fixed in the upstream library: https://github.com/awslabs/aws-sam-cli/pull/1634

**Comment by buckett** [comment]
$ sam --version
    SAM CLI, version 0.37.0

**Comment by buckett** [comment]
Ok so this was fixed in: https://github.com/awslabs/aws-sam-cli/releases/tag/v0.38.0

Sorry for the noise.
