### ISSUE TITLE
Unable to deploy Lamdba Function with SAM_CLI_TELEMETRY=0

### ISSUE THREAD

**Issue by iolbr** [awslabs/serverless-application-model#1355]
**Description:**
When deploying function to AWS using sam I get a stacktrace related to a timeout of due to the fact that aws-serverless-tools-telemetry.us-west-2.amazonaws.com is not reachable. When I turn off telemetry by setting  export SAM_CLI_TELEMETRY=0 stacktrace remains the same. My expectation would be that by setting the parameter this part of the code is no longer executed?!

**Steps to reproduce the issue:**
1. Build hello world demo app with python 3.6
2. export SAM_CLI_TELEMETRY=0
3.sam deploy --guided

**Observed result:**
Configuring SAM deploy
======================

	Looking for samconfig.toml :  Not found

	Setting default arguments for 'sam deploy'
	=========================================
	Stack Name [sam-app]: 
	AWS Region [us-east-1]: eu-central-1               
	#Shows you resources changes to be deployed and require a 'Y' to initiate deploy
	Confirm changes before deploy [y/N]: 
	#SAM needs permission to be able to create roles to connect to the resources in your template
	Allow SAM CLI IAM role creation [Y/n]: 
	Save arguments to samconfig.toml [Y/n]: 

	Looking for resources needed for deployment: Found!
Traceback (most recent call last):
  File "/home/io/python/aws-sam/bin/sam", line 11, in <module>
    sys.exit(cli())
  File "/home/io/python/aws-sam/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/io/python/aws-sam/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/io/python/aws-sam/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/io/python/aws-sam/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/io/python/aws-sam/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/io/python/aws-sam/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/io/python/aws-sam/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/io/python/aws-sam/lib/python3.6/site-packages/samcli/lib/telemetry/metrics.py", line 48, in wrapped
    return func(*args, **kwargs)
  File "/home/io/python/aws-sam/lib/python3.6/site-packages/samcli/commands/deploy/command.py", line 187, in cli
    ctx.profile,
  File "/home/io/python/aws-sam/lib/python3.6/site-packages/samcli/commands/deploy/command.py", line 245, in do_cli
    stack_name, s3_bucket, region, profile, confirm_changeset, _parameter_override_keys, parameter_overrides
  File "/home/io/python/aws-sam/lib/python3.6/site-packages/samcli/commands/deploy/command.py", line 345, in guided_deploy
    s3_bucket = manage_stack(profile=profile, region=region)
  File "/home/io/python/aws-sam/lib/python3.6/site-packages/samcli/lib/bootstrap/bootstrap.py", line 37, in manage_stack
    return _create_or_get_stack(cloudformation_client)
  File "/home/io/python/aws-sam/lib/python3.6/site-packages/samcli/lib/bootstrap/bootstrap.py", line 71, in _create_or_get_stack
    outputs = stack["Outputs"]
KeyError: 'Outputs'

**Expected result:**

**Comment by iolbr** [comment]
Looks like the stacktrace has nothing to do with the telemetry option. Seems to be an issue with the sam eployment of the sample helloworld.py. Sorry.
