### ISSUE TITLE
!Ref not working for StepFunction in a lambda call

### ISSUE THREAD

**Issue by ospfranco** [awslabs/serverless-application-model#1477]
**Description:**

Hi, I'm trying to invoke a state machine using a lambda function.

I started by somewhat copying this repo: https://github.com/mmuppidi/apigateway-stepfunctions-sam/blob/master/stack.yaml

so, here is my template file:

```YAML
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  strest

  Sample SAM Template for strest

Globals:
  Function:
    Timeout: 3

Resources:
  PublicApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      # TracingEnabled: true
      DefinitionBody:
        swagger: "2.0"
        info:
          title: "StrestApi"
        paths:
          /start: # api gateway invokes lambda synchronously, which in turn invokes the stepfunction and waits for its final result
            get:
              produces:
                - "application/json"
              responses:
                "200":
                  description: "200 response"
                  schema:
                    $ref: "#/definitions/Empty"
                  headers:
                    Access-Control-Allow-Headers:
                    type: "string"
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: "200"
                    headers:
                      Access-Control-Allow-Headers:
                      type: "'*'"
                httpMethod: GET
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${StartFunction.Arn}/invocations

        definitions:
          Empty:
            type: "object"
            title: "Empty Schema"

  # Role which allows step functions to invoke lambda functions
  StatesExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: "sts:AssumeRole"
      Path: "/"
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "lambda:InvokeFunction"
                Resource: "*"

  # State machine
  MyStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: !GetAtt StatesExecutionRole.Arn
      DefinitionString: !Sub |-
        {
          "StartAt": "execute",
          "Comment": "State machine for executing the strest main loop",
          "States": {
            "execute": {
              "Type": "Task",
              "Resource": "${ExecutorFunction.Arn}",
              "Comment": "Run the Executor Lambda function",
              "End": true
            }
          }
        }

  # LAMBDAS
  StartFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Starts the state machine
      CodeUri: dist/start
      Handler: start.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          STEP_FUNCTION_ARN: !Ref MyStateMachine
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: "Allow" # step function permissions open for now
              Action:
                - states:*
              Resource: "*"
      Events:
        ExecSFNResource:
          Type: Api
          Properties:
            RestApiId: !Ref PublicApi
            Path: /start
            Method: GET

  ExecutorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: executor/executor.handler
      Runtime: nodejs12.x
```

The problem is, when I start the api (sam local start-api) and call the endpoint, the function starts executing, but when I inspect the environment variable I get the name value and not the ARN.

here is the code of the start function:

```typescript
import AWS from "aws-sdk";

export async function handler(event: any, context: any) {
  let stepFunctionArn = process.env.STEP_FUNCTION_ARN;

  console.log("marker0 stepFunctionArn", stepFunctionArn);

  let params = {
    stateMachineArn: stepFunctionArn!,
    name: "Execution lambda " + new Date().toString()
  };
  console.log("marker 1");

  let sf_client = new AWS.StepFunctions();
  console.log("marker 2");

  let res = await sf_client.startExecution(params).promise();

  console.log("marker 3", res);

  return {};
}

```

And the console output is:

```
START RequestId: 4c1c0dea-0178-1612-d8cb-e45cec3c5d9a Version: $LATEST
[1] 2020-02-28T21:58:40.879Z	4c1c0dea-0178-1612-d8cb-e45cec3c5d9a	INFO	marker0 stepFunctionArn MyStateMachine
[1] 2020-02-28T21:58:40.883Z	4c1c0dea-0178-1612-d8cb-e45cec3c5d9a	INFO	marker 1
[1] 2020-02-28T21:58:40.890Z	4c1c0dea-0178-1612-d8cb-e45cec3c5d9a	INFO	marker 2
[1] 2020-02-28T21:58:42.183Z	4c1c0dea-0178-1612-d8cb-e45cec3c5d9a	ERROR	Invoke Error 	{"errorType":"InvalidArn","errorMessage":"Invalid Arn: 'Invalid ARN prefix: MyStateMachine'","code":"InvalidArn","message":"Invalid Arn: 'Invalid ARN prefix: MyStateMachine'","time":"2020-02-28T21:58:42.179Z","requestId":"74aec8d6-40f7-4e64-a61e-8298fc75cd8a","statusCode":400,"retryable":false,"retryDelay":23.361184043342842,"stack":["InvalidArn: Invalid Arn: 'Invalid ARN prefix: MyStateMachine'","    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:51:27)","    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)","    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)","    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:683:14)","    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)","    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)","    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10","    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)","    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:685:12)","    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"]}
```

**Observed result:**
`!Ref MyStateMachine` is not working, it does not return the ARN value
**Expected result:**
`!Ref MyStateMachine` correctly sets the ARN for the environment variable

P.S. I also tried changing `!Ref MyStateMachine` to `!GetAtt MyStateMachine.Arn` and something completely wrong is returned, instead of a statemachine arn being returned a lambda arn is returned and then I get a invalid arn for this context when trying to start the state machine in the start function.

AWS-SAM-CLI version: 0.43.0

**Comment by ShreyaGangishetty** [comment]
@ospfranco Please post this on StackOverflow or reach out to AWS Support for this issue. This doesn't seem to be like a SAM issue
