### ISSUE TITLE
Running sam --validate produces an AttributeError

### ISSUE THREAD

**Issue by brukhabtu** [awslabs/serverless-application-model#1565]
**Description:**

**Steps to reproduce the issue:**
1. sam validate

**Observed result:**
```Traceback (most recent call last):
  File "/usr/local/bin/sam", line 11, in <module>
    load_entry_point('aws-sam-cli==0.47.0', 'console_scripts', 'sam')()
  File "/usr/local/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/samcli/lib/telemetry/metrics.py", line 96, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/usr/local/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/samcli/lib/telemetry/metrics.py", line 62, in wrapped
    return_value = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/samcli/commands/validate/validate.py", line 27, in cli
    do_cli(ctx, template_file)  # pragma: no cover
  File "/usr/local/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/samcli/commands/validate/validate.py", line 47, in do_cli
    validator.is_valid()
  File "/usr/local/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/samcli/commands/validate/lib/sam_template_validator.py", line 60, in is_valid
    template = sam_translator.translate(sam_template=self.sam_template, parameter_values={})
  File "/usr/local/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/samtranslator/translator/translator.py", line 88, in translate
    sam_parameter_values.add_pseudo_parameter_values()
  File "/usr/local/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/samtranslator/sdk/parameter.py", line 73, in add_pseudo_parameter_values
    if region.startswith("cn-"):
AttributeError: 'NoneType' object has no attribute 'startswith'```

**Expected result:**
The function to to tell me whether or not my yml file is valid.

**Template.yml**
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  recipe-monster

  Sample SAM Template for recipe-monster

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  RecipeMonsterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        RecipeMonster:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /recipes
            Method: POST

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RecipeMonsterApi:
    Description: "API Gateway endpoint URL for Prod stage for Recipe Monster function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  RecipeMonsterFunction:
    Description: "Recipe Monster Lambda Function ARN"
    Value: !GetAtt RecipeMonsterFunction.Arn
  RecipeMonsterFunctionIamRole:
    Description: "Implicit IAM Role created for Recipe Monster function"
    Value: !GetAtt RecipeMonsterFunctionRole.Arn

```

**Comment by keetonian** [comment]
@brukhabtu SAM expects a region to be set in the boto3 or aws configuration in order to do validation. If you run `aws configure` and set a region, this validate call should work.
