### ISSUE TITLE
AWS `sam build` literally destroying and corrupting filesystem - "The tag present in the reparse point buffer is invalid"

### ISSUE THREAD

**Issue by Gunt-r** [awslabs/serverless-application-model#1642]
**Description:**

Corrupted build filesystem. Failed build. Inability to delete files EVEN with extreme measures like `CHKDSK` or bash `rm`. Filesystem is on Onedrive which has seen this same error occur but in different contexts and with `CHKDSK` able to fix the problem.

Win 10 Pro 1903

**Steps to reproduce the issue:**
1. I'd assume have a repository in Onedrive
2. Have a SAM application
3. `sam build` and deploy
4. Make some sort of change and `sam build`
5. That should reproduce issue.

**Observed result:**

Broken `.aws-sam` build location. Inability to recover or delete file. Can't continue deployment in current repository.

Here is the build error:

`OSError: [WinError 4393] The tag present in the reparse point buffer is invalid: '.aws-sam\\build\\{function-name}\\botocore\\data\\dynamodbstreams\\2012-08-10'`

Here is the stacktrace:

```
Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 96, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 62, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 129, in cli
    mode,
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 179, in do_cli
    mode=mode,
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 67, in __enter__
    self._build_dir = self._setup_build_dir(self._build_dir, self._clean)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 89, in _setup_build_dir
    shutil.rmtree(build_dir)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 516, in rmtree
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 395, in _rmtree_unsafe
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 395, in _rmtree_unsafe
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 395, in _rmtree_unsafe
  [Previous line repeated 2 more times]
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 377, in _rmtree_unsafe
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\shutil.py", line 374, in _rmtree_unsafe
OSError: [WinError 4393] The tag present in the reparse point buffer is invalid: '.aws-sam\\build\\printAccountBalanceFunction\\botocore\\data\\dynamodbstreams\\2012-08-10'
```

![image](https://user-images.githubusercontent.com/35857175/86298517-47b28780-bc41-11ea-9b1f-340765af771b.png)

**Expected result:**

Complete build and no errors.

**Comment by Gunt-r** [comment]
After further testing, I have determined that there is a good chance the issue only happens because I am attempting to build within a onedrive repository. I have determined this because of the following

1. I built twice in two separate repositories and occured the exact same issue. Keep in mind that these two separate repositories contained the same files (minus the broken build repo obviously).
2. Upon researching this error, I found excessive mention of the issue with links to onedrive, meaning that there is a good chance it is because of the fact that I am building WITHIN a onedrive repo that that is what is causing the problem. 
3. I then copied the same project files that PREVIOUSLY failed builds in onedrive to a new repo within windows DOCUMENTS. I built there - did almost the same thing as I do with the repo's in onedrive and encountered no problems. The only different thing I did that MAY have affected the test was after building once, I deleted (moved to recycle bin) the final build files to see if they were already broken at that point. I then restored them to continue the process. After deploying, I did the same delete thingy and again determined that it was not broken. Finally, after a second build, I did the same delete thing again and it still was not broken.

As such, the problem can be fixed by not using onedrive.
