### ISSUE TITLE
stdin for sam local doesn't have correct encoding

### ISSUE THREAD

**Issue by koblas** [awslabs/serverless-application-model#478]
**stdin for sam local doesn't have correct encoding**

When piping data to ```sam local invoke``` you will get UnicodeEncodeError when preseted with non-ASCII unicode streams.

**Steps to reproduce the issue:**
1. Make sure you're using the python2.7 SAM
2.  Create a test file like :  ```{ "city": "Tromsø" }```  -- the 'o' character is non-ASCII character
3.  ```cat test.json | sam local invoke```

Note: this only reproduces when it's piped in (via stdin) rather than provided as a '-e file'

**Observed result:**

    Traceback (most recent call last):
      File "/Users/koblas/.virtualenvs/aws-sam/bin/sam", line 11, in <module>
        sys.exit(cli())
      File "/Users/koblas/.virtualenvs/aws-sam/lib/python2.7/site-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/Users/koblas/.virtualenvs/aws-sam/lib/python2.7/site-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/Users/koblas/.virtualenvs/aws-sam/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/Users/koblas/.virtualenvs/aws-sam/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/Users/koblas/.virtualenvs/aws-sam/lib/python2.7/site-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/Users/koblas/.virtualenvs/aws-sam/lib/python2.7/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/Users/koblas/.virtualenvs/aws-sam/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
        return ctx.invoke(f, obj, *args[1:], **kwargs)
      File "/Users/koblas/.virtualenvs/aws-sam/lib/python2.7/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/Users/koblas/.virtualenvs/aws-sam/lib/python2.7/site-packages/samcli/commands/local/invoke/cli.py", line 44, in cli
        docker_network, log_file, skip_pull_image, profile)  # pragma: no cover
      File "/Users/koblas/.virtualenvs/aws-sam/lib/python2.7/site-packages/samcli/commands/local/invoke/cli.py", line 76, in do_cli
        stderr=context.stderr)
      File "/Users/koblas/.virtualenvs/aws-sam/lib/python2.7/site-packages/samcli/commands/local/lib/local_lambda.py", line 80, in invoke
        stdout=stdout, stderr=stderr)
      File "/Users/koblas/.virtualenvs/aws-sam/lib/python2.7/site-packages/samcli/local/lambdafn/runtime.py", line 68, in invoke
        env_vars = environ.resolve()
      File "/Users/koblas/.virtualenvs/aws-sam/lib/python2.7/site-packages/samcli/local/lambdafn/env_vars.py", line 100, in resolve
        result[name] = self._stringify_value(value)
      File "/Users/koblas/.virtualenvs/aws-sam/lib/python2.7/site-packages/samcli/local/lambdafn/env_vars.py", line 195, in _stringify_value
        result = str(value)
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xf8' in position 16: ordinal not in range(128)

**Expected result:**

Lambda function should run in the sam way as if invoked as ```sam local invoke -e test.json```

**Comment by brettstack** [comment]
Please open an issue in the SAM CLI repo
