### ISSUE TITLE
Plugin 'ImplicitApiPlugin' raised an exception: 'Method' - Unhelpful exception message

### ISSUE THREAD

**Issue by revolutionisme** [awslabs/serverless-application-model#621]
**Description:**

Running sam local start-api results in the following error:

```
BKF-11118:cloudformation-stack d303$ sam local start-api -t stack/appspec.yaml 
2018-10-09 14:32:35 Plugin 'ImplicitApiPlugin' raised an exception: 'Method'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/samtranslator/plugins/__init__.py", line 126, in act
    getattr(plugin, method_name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/samtranslator/plugins/api/implicit_api_plugin.py", line 73, in on_before_transform_template
    self._process_api_events(function, api_events, template)
  File "/usr/local/lib/python3.6/site-packages/samtranslator/plugins/api/implicit_api_plugin.py", line 127, in _process_api_events
    self._add_api_to_swagger(logicalId, event_properties, template)
  File "/usr/local/lib/python3.6/site-packages/samtranslator/plugins/api/implicit_api_plugin.py", line 189, in _add_api_to_swagger
    method = event_properties["Method"]
KeyError: 'Method'
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/samcli/commands/local/start_api/cli.py", line 54, in cli
    docker_volume_basedir, docker_network, log_file, skip_pull_image, profile, region)  # pragma: no cover
  File "/usr/local/lib/python3.6/site-packages/samcli/commands/local/start_api/cli.py", line 80, in do_cli
    aws_region=region) as invoke_context:
  File "/usr/local/lib/python3.6/site-packages/samcli/commands/local/cli_common/invoke_context.py", line 117, in __enter__
    self._function_provider = SamFunctionProvider(self._template_dict)
  File "/usr/local/lib/python3.6/site-packages/samcli/commands/local/lib/sam_function_provider.py", line 40, in __init__
    self.template_dict = SamBaseProvider.get_template(template_dict)
  File "/usr/local/lib/python3.6/site-packages/samcli/commands/local/lib/sam_base_provider.py", line 17, in get_template
    template_dict = SamTranslatorWrapper(template_dict).run_plugins()
  File "/usr/local/lib/python3.6/site-packages/samcli/lib/samlib/wrapper.py", line 67, in run_plugins
    parser.parse(template_copy, all_plugins)  # parse() will run all configured plugins
  File "/usr/local/lib/python3.6/site-packages/samcli/lib/samlib/wrapper.py", line 120, in parse
    sam_plugins.act(LifeCycleEvents.before_transform_template, sam_template)
  File "/usr/local/lib/python3.6/site-packages/samtranslator/plugins/__init__.py", line 132, in act
    raise ex
  File "/usr/local/lib/python3.6/site-packages/samtranslator/plugins/__init__.py", line 126, in act
    getattr(plugin, method_name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/samtranslator/plugins/api/implicit_api_plugin.py", line 73, in on_before_transform_template
    self._process_api_events(function, api_events, template)
  File "/usr/local/lib/python3.6/site-packages/samtranslator/plugins/api/implicit_api_plugin.py", line 127, in _process_api_events
    self._add_api_to_swagger(logicalId, event_properties, template)
  File "/usr/local/lib/python3.6/site-packages/samtranslator/plugins/api/implicit_api_plugin.py", line 189, in _add_api_to_swagger
    method = event_properties["Method"]
KeyError: 'Method'
```

**Steps to reproduce the issue:**
1. Install sam-cli using pip install
2. Install docker using brew cask install
3. run sam-cli and pass template as a parameter

**Observed result:**
Exception shown above

**Expected result:**

**Additional environment details (Ex: Windows, Mac, Amazon Linux etc)**
Mac OS Sierra version: 10.12.6

**Output of `sam --version`**:
SAM CLI, version 0.6.0

**Optional Debug logs**:

`Add --debug flag to command you are running`

Same output as above, with/without --debug flag

Issue was originally posted [here](https://github.com/awslabs/aws-sam-cli/issues/700) and the resolution was to add method in the serveless::function api. Allthough this passed the sam validation check as well.

**Comment by keetonian** [comment]
Thank you for posting this. The SAM validation requires several updates; I added a tag for when these updates are designed and implemented.

**Comment by keetonian** [comment]
Closing in favor of https://github.com/awslabs/serverless-application-model/issues/675
