### ISSUE TITLE
Getting an Attribute Error after running sam invoke local command

### ISSUE THREAD

**Issue by Private-SO** [awslabs/serverless-application-model#626]
This a question.

Hi,

Installed SAM in `/Scripts` folder and made an environment variable for it to access globally.

Machine Environment
Windows 8.1 
Installed docker through docker-tool-box

D:\Python>pip --version
pip 18.0 from d:\python\lib\site-packages\pip (python 3.6)

D:\Python>sam --version
SAM CLI, version 0.6.0

D:\Python>python --version
Python 3.6.4

D:\Python>pip --version
pip 18.0 from d:\python\lib\site-packages\pip (python 3.6)

D:\Python>docker --version
Docker version 18.03.0-ce, build 0520e24302

My index.js

```
  'use strict';

  exports.handler= function(event, context, callback) {
      
      console.log('DEBUG: Name is ' + event.name);
      callback(null, "Hello " + event.name);
    };
```

template.yml

```
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: A Simple Hello World Project
Resources:
  GetHelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs8.10
      Handler: index.handler
```
events.json

```
{
    "name" : "Bob"
}
```

After running the command `sam local invoke -e events.json GetHelloWorld --debug`

```
2018-10-03 22:59:22 local invoke command is called
2018-10-03 22:59:22 1 resources found in the template
2018-10-03 22:59:22 Found Serverless function with name='GetHelloWorld' and CodeUri='.'
2018-10-03 22:59:22 Trying paths: <filter object at 0x0000003AA8244B70>
2018-10-03 22:59:22 No config file found
2018-10-03 22:59:22 Starting new HTTPS connection (1): 192.168.9x.1xx:2376
2018-10-03 22:59:23 https://192.168.9x.1xx:2376 "GET /v1.24/_ping HTTP/1.1" 200 2
2018-10-03 22:59:23 Trying paths: <filter object at 0x0000003AA821D780>
2018-10-03 22:59:23 No config file found
2018-10-03 22:59:23 Found one Lambda function with name 'GetHelloWorld'
2018-10-03 22:59:23 Invoking index.handler (nodejs8.10)
2018-10-03 22:59:23 No environment variables found for function 'GetHelloWorld'
2018-10-03 22:59:23 Environment variables overrides data is standard format
2018-10-03 22:59:23 Loading AWS credentials from session with profile 'None'
2018-10-03 22:59:23 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2018-10-03 22:59:23 Changing event name from before-call.apigateway to before-call.api-gateway
2018-10-03 22:59:23 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2018-10-03 22:59:23 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2018-10-03 22:59:23 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2018-10-03 22:59:23 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2018-10-03 22:59:23 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2018-10-03 22:59:23 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2018-10-03 22:59:23 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2018-10-03 22:59:23 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2018-10-03 22:59:23 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2018-10-03 22:59:23 Loading variable profile from defaults.
2018-10-03 22:59:23 Loading variable config_file from defaults.
2018-10-03 22:59:23 Loading variable credentials_file from defaults.
2018-10-03 22:59:23 Loading variable data_path from defaults.
2018-10-03 22:59:23 Loading variable profile from defaults.
2018-10-03 22:59:23 Loading variable credentials_file from defaults.
2018-10-03 22:59:23 Loading variable config_file from defaults.
2018-10-03 22:59:23 Loading variable profile from defaults.
2018-10-03 22:59:23 Loading variable metadata_service_timeout from defaults.
2018-10-03 22:59:23 Loading variable profile from defaults.
2018-10-03 22:59:23 Loading variable metadata_service_num_attempts from defaults.
2018-10-03 22:59:23 Loading variable profile from defaults.
2018-10-03 22:59:23 Looking for credentials via: env
2018-10-03 22:59:23 Looking for credentials via: assume-role
2018-10-03 22:59:23 Looking for credentials via: shared-credentials-file
2018-10-03 22:59:23 Found credentials in shared credentials file: ~/.aws/credentials
2018-10-03 22:59:23 Loading variable profile from defaults.
2018-10-03 22:59:23 Loading variable profile from defaults.
2018-10-03 22:59:23 Loading variable region from config file with value 'ap-south-1'.
2018-10-03 22:59:23 Loading variable profile from defaults.
2018-10-03 22:59:23 Loading variable profile from defaults.
2018-10-03 22:59:23 Loading variable region from config file with value 'ap-south-1'.
2018-10-03 22:59:23 Loading variable profile from defaults.
2018-10-03 22:59:23 Loading variable profile from defaults.
2018-10-03 22:59:23 Loading variable region from config file with value 'ap-south-1'.
2018-10-03 22:59:23 Resolving code path. Cwd=D:\TECH\DockerTest\TestLocal, CodeUri=.
2018-10-03 22:59:23 Resolved absolute path to code is D:\TECH\DockerTest\TestLocal
2018-10-03 22:59:23 Code D:\TECH\DockerTest\TestLocal is not a zip/jar file
2018-10-03 22:59:23 Trying paths: <filter object at 0x0000003AA8282978>
2018-10-03 22:59:23 No config file found
2018-10-03 22:59:23 Container was not created. Skipping deletion
Traceback (most recent call last):
  File "d:\python\lib\site-packages\samcli\local\docker\manager.py", line 108, in has_image
    self.docker_client.images.get(image_name)
AttributeError: 'function' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\Scripts\sam-script.py", line 11, in <module>
    load_entry_point('aws-sam-cli==0.6.0', 'console_scripts', 'sam')()
  File "d:\python\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "d:\python\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "d:\python\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\python\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\python\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\python\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "d:\python\lib\site-packages\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "d:\python\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "d:\python\lib\site-packages\samcli\commands\local\invoke\cli.py", line 49, in cli
    docker_volume_basedir, docker_network, log_file, skip_pull_image, profile, region)  # pragma: no cover
  File "d:\python\lib\site-packages\samcli\commands\local\invoke\cli.py", line 90, in do_cli
    stderr=context.stderr)
  File "d:\python\lib\site-packages\samcli\commands\local\lib\local_lambda.py", line 80, in invoke
    self.local_runtime.invoke(config, event, debug_context=self.debug_context, stdout=stdout, stderr=stderr)
  File "d:\python\lib\site-packages\samcli\local\lambdafn\runtime.py", line 79, in invoke
    self._container_manager.run(container)
  File "d:\python\lib\site-packages\samcli\local\docker\manager.py", line 52, in run
    if not self.has_image(image_name) or not self.skip_pull_image:
  File "d:\python\lib\site-packages\samcli\local\docker\manager.py", line 110, in has_image
    except docker.errors.ImageNotFound:
AttributeError: module 'docker.errors' has no attribute 'ImageNotFound'
```

Thanks
Any help is appreciated

**Comment by brettstack** [comment]
Hopefully our friends over at https://github.com/awslabs/aws-sam-cli/issues can help you out.
