### ISSUE TITLE
Invalid attribute throws uncaught exception in samtranslator.

### ISSUE THREAD

**Issue by emilbryggare** [awslabs/serverless-application-model#654]
Hi! 

I'm reporting a minor issue in samtranslator.

An invalid attribute in template.yaml raises an uncaught exception from samtranslator. I discovered this issue when using [cfn-lint](https://github.com/awslabs/cfn-python-lint). I already reported the error on their side in [#436](https://github.com/awslabs/cfn-python-lint/issues/436) and they fixed it in [#440](https://github.com/awslabs/cfn-python-lint/issues/440).

Here is a sample template. If MyInvalidAttr is replaced with a correct attribute eg Name then the template works.
```
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 3

Resources:
  MyTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: MyTable
      PrimaryKey:
        MyInvalidAttr: id
        Type: String
```
Observed result:
```
$ sam validate
2018-11-08 21:00:18 Found credentials in shared credentials file: ~/.aws/credentials
Traceback (most recent call last):
  File "/Users/emilbryggare/Library/Python/2.7/bin/sam", line 11, in <module>
    sys.exit(cli())
  File "/Users/emilbryggare/Library/Python/2.7/lib/python/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/emilbryggare/Library/Python/2.7/lib/python/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/emilbryggare/Library/Python/2.7/lib/python/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/emilbryggare/Library/Python/2.7/lib/python/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/emilbryggare/Library/Python/2.7/lib/python/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/emilbryggare/Library/Python/2.7/lib/python/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/emilbryggare/Library/Python/2.7/lib/python/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/emilbryggare/Library/Python/2.7/lib/python/site-packages/samcli/commands/validate/validate.py", line 30, in cli
    do_cli(ctx, template)  # pragma: no cover
  File "/Users/emilbryggare/Library/Python/2.7/lib/python/site-packages/samcli/commands/validate/validate.py", line 44, in do_cli
    validator.is_valid()
  File "/Users/emilbryggare/Library/Python/2.7/lib/python/site-packages/samcli/commands/validate/lib/sam_template_validator.py", line 83, in is_valid
    parameter_values={})
  File "/Users/emilbryggare/Library/Python/2.7/lib/python/site-packages/samtranslator/translator/translator.py", line 72, in translate
    translated = macro.to_cloudformation(**kwargs)
  File "/Users/emilbryggare/Library/Python/2.7/lib/python/site-packages/samtranslator/model/sam_resources.py", line 537, in to_cloudformation
    dynamodb_resources = self._construct_dynamodb_table()
  File "/Users/emilbryggare/Library/Python/2.7/lib/python/site-packages/samtranslator/model/sam_resources.py", line 546, in _construct_dynamodb_table
    'AttributeName': self.PrimaryKey['Name'],
KeyError: 'Name'
```

Expected result:
```
$sam validate
Not a valid template:
Invalid attribute 'MyInvalidAttr' on line 17 in template.yaml.
```
**Steps to reproduce the issue:**
1. Use the template.yaml mentioned above.
2. Try to validate the template using sam validate
3. Uncaught exception.

**Comment by keetonian** [comment]
This is a known issue and is a priority for us to fix.

**Comment by keetonian** [comment]
Closing in favor of https://github.com/awslabs/serverless-application-model/issues/675
