### ISSUE TITLE
sam-translate.py fails with 'TypeError: datetime.date(2012, 10, 17) is not JSON serializable'

### ISSUE THREAD

**Issue by lestephane** [awslabs/serverless-application-model#903]
I have  a SAM template with a CloudWatch role defined as follows

```text
  CloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: apigateway.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonApiGatewayPushToCloudWatchLogs
```

When I run the sam-translate.py command, I get an error related to the 2012-10-17 date

```
...
TypeError: datetime.date(2012, 10, 17) is not JSON serializable
```

**Steps to reproduce the issue:**
1. mkvirtualenv for a 2.7.16 python environment
2. pip install  -r requirements/base.txt
3. pip install  -r requirements/dev.txt
3. aws cloudformation package ... --output-template-file=packaged.yml
4. sam-translate.py     --template-file=packaged.yml

**Observed result:**
```text
Traceback (most recent call last):
  File "../serverless-application-model/bin/sam-translate.py", line 141, in <module>
    transform_template(input_file_path, output_file_path)
  File "../serverless-application-model/bin/sam-translate.py", line 100, in transform_template
    cloud_formation_template, indent=2)
  File "/home/lestephane/Python/Python-2.7.16/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/home/lestephane/Python/Python-2.7.16/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/home/lestephane/Python/Python-2.7.16/lib/python2.7/json/encoder.py", line 434, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "/home/lestephane/Python/Python-2.7.16/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/home/lestephane/Python/Python-2.7.16/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/home/lestephane/Python/Python-2.7.16/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/home/lestephane/Python/Python-2.7.16/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/home/lestephane/Python/Python-2.7.16/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
    for chunk in chunks:
  File "/home/lestephane/Python/Python-2.7.16/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/home/lestephane/Python/Python-2.7.16/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.date(2012, 10, 17) is not JSON serializable
```

**Expected result:**

**Comment by lestephane** [comment]
If I comment out the problematic resource (to see how far i can go), I get the same error on the next resource that uses a PolicyDocument with the same version (`2012-10-17`)

```text
  TrafficLifecycleStatusPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${AWS::StackName}LifecycleStatusPolicy"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: "CanPutDeploymentStatus"
            Effect: "Allow"
            Action:
              - "codedeploy:PutLifecycleEventHookExecutionStatus"
            Resource:
              !Sub 'arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*'
      Roles:
        - !Ref TestRoleName
```

**Comment by chrisoverzero** [comment]
As a workaround (in case you didn’t already know), the date value can be wrapped in quotes.

**Comment by lestephane** [comment]
Good to know, thanks

**Comment by praneetap** [comment]
Closing issue since there is a workaround

**Comment by the0ffh** [comment]
> Closing issue since there is a workaround

Workarounds FTW!!
